# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39d397d1371377f00b5989c6715f3605f6739a97e0495d058bd93a631c58f609e2e455668b13e47af7f38bdefa8c4e69a7ffca03bb1cd25be2e7b3927ffba5d8

test:
  secret_key_base: ac1dd7e548848c1e89abd1bf6b921a806082984d461d7ff3bd773cbdcc7f51145f4748256c92bf0c6160e2ea676a41e90dc43326a72ca7cc6e57705eed0c0276

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
